title: Computer Vision & Machine Learning 
email: siteURL@gmail.com
description: Expertise in Computer Vision and Language Models
baseurl: "/"  
url: "https://pirahansiah.com"  
twitter_username: pirahansiah
github_username:  pirahansiah

markdown: kramdown
permalink: /:year/:title:output_ext

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  linkify: true