# Site settings
title: Farshid Pirahansiah
author: Farshid Pirahansiah
url: https://www.pirahansiah.com
baseurl: ""
description: Computer Vision & AI Engineer

# Jekyll settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "contents"
    values:
      layout: farshid_default

# Plugins
plugins:
  - jekyll-feed

include:
  - contents

# Exclude
exclude:
  - README.md
  - run.sh
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .git/
  - .gitignore
  - CNAME
  - Ads.txt
  - contents/farshid-ai-cv-llm-site.md
  - scripts/
