# Site settings
title: Farshid
email: family name gmail
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision
  LLMs
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://pirahansiah.com" # the base hostname & protocol for your site
twitter_username: pirahansiah
github_username:  pirahansiah

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext